branch-defaults:
  main:
    environment: x23108568-lifecarehospital-env
    group_suffix: null
global:
  application_name: x23108568-lifecarehospital
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
