# Generated by Django 2.1.15 on 2023-10-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_bookappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='depname',
            field=models.CharField(default='YourDefaultValue', max_length=255),
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='paddress',
            field=models.CharField(max_length=600),
        ),
    ]
