# Generated by Django 2.1.15 on 2023-10-20 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='depName',
            new_name='depname',
        ),
    ]
