# Generated by Django 2.1.15 on 2023-10-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='docspec',
            new_name='Qualification',
        ),
    ]
